import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { spawn, ChildProcess } from "node:child_process";
import path from "node:path";
import fs from "node:fs";
import os from "node:os";

describe("Real HTTP isolation WITH valid admin config", () => {
  let serverProcess: ChildProcess;
  const PORT = 43211;
  const BASE_URL = `http://localhost:${PORT}`;

  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "timeless-admin-http-"));
  const dbPath = path.join(tempDir, "rate-limit.db");
  const siteContentPath = path.join(tempDir, "site-content.json");
  const defaultContentPath = path.resolve(__dirname, "../app/content/default-site-content.json");

  beforeAll(async () => {
    fs.copyFileSync(defaultContentPath, siteContentPath);

    return new Promise((resolve, reject) => {
      serverProcess = spawn("npm", ["run", "start"], {
        cwd: path.resolve(__dirname, ".."),
        env: {
          ...process.env,
          PORT: String(PORT),
          NODE_ENV: "production",
          PUBLIC_SITE_URL: BASE_URL,
          CONTACT_RATE_LIMIT_SECRET: "test-secret",
          RATE_LIMIT_DB_PATH: dbPath,
          SMTP_HOST: "localhost",
          SMTP_PORT: "2525",
          SMTP_USER: "test",
          SMTP_PASS: "test",
          SMTP_FROM: "from@example.com",
          SMTP_TO: "to@example.com",
          CONTACT_RATE_LIMIT_MAX: "10",
          TRUST_PROXY: "true",
          // The hash below is for password 'test' generated by argon2id
          ADMIN_PASSWORD_HASH: "$argon2id$v=19$m=19456,t=2,p=1$xDSx00u+uSs9AcMqypmthw$ubmjWhg1XWL+Yp496qb5LLlTx0FK4lwqy9pvKa5ills",
          ADMIN_SESSION_SECRET: "12345678901234567890123456789012", // 32 chars
          SITE_CONTENT_PATH: siteContentPath,
          PORTFOLIO_CONTENT_PATH: path.join(tempDir, "portfolio.json"),
          PORTFOLIO_MEDIA_PATH: path.join(tempDir, "media")
        },
      });

      const timeout = setTimeout(() => reject(new Error("Server startup timeout")), 15000);

      serverProcess.stdout?.on("data", (data) => {
        if (data.toString().includes(String(PORT))) {
          clearTimeout(timeout);
          resolve(undefined);
        }
      });
      serverProcess.stderr?.on("data", (data) => console.error("Server error:", data.toString()));
      serverProcess.on("error", (err) => {
        clearTimeout(timeout);
        reject(err);
      });
      serverProcess.on("exit", (code) => {
        clearTimeout(timeout);
        if (code !== 0 && code !== null) {
          reject(new Error(`Server exited with code ${code}`));
        }
      });
    });
  });

  afterAll(() => {
    if (serverProcess) serverProcess.kill();
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("GET /admin/pricing sans session -> 302 vers /admin", async () => {
    const res = await fetch(`${BASE_URL}/admin/pricing`, { redirect: "manual" });
    expect(res.status).toBe(302);
    expect(res.headers.get("Location")).toBe("/admin");
  });

  it("GET /admin/settings sans session -> 302 vers /admin", async () => {
    const res = await fetch(`${BASE_URL}/admin/settings`, { redirect: "manual" });
    expect(res.status).toBe(302);
    expect(res.headers.get("Location")).toBe("/admin");
  });

  it("POST with anonymous signed cookie -> 302 and clear cookie without touching file", async () => {
    const getRes = await fetch(`${BASE_URL}/admin`);
    const cookies = getRes.headers.get("Set-Cookie");
    const text = await getRes.text();
    const csrfMatch = text.match(/name="csrfToken" value="([^"]+)"/);
    const csrfToken = csrfMatch ? csrfMatch[1] : "";

    const beforeData = fs.readFileSync(siteContentPath);
    const beforeFiles = fs.readdirSync(tempDir);

    const checkRoute = async (route: string) => {
      const res = await fetch(`${BASE_URL}/admin/${route}`, {
        method: "POST",
        body: new URLSearchParams({ csrfToken, pricing: "{}", business: "{}" }),
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          "Origin": BASE_URL,
          "Cookie": cookies || "",
          "x-forwarded-for": "127.0.0.1"
        },
        redirect: "manual",
      });

      expect(res.status).toBe(302);
      expect(res.headers.get("Location")).toBe("/admin");

      const setCookie = res.headers.get("Set-Cookie") || "";
      expect(setCookie).toContain("__admin_session=");
      expect(setCookie.toLowerCase()).toMatch(/max-age=0|expires=thu, 01 jan 1970/);

      expect(fs.readFileSync(siteContentPath)).toEqual(beforeData);
      expect(fs.readdirSync(tempDir)).toEqual(beforeFiles);
    };

    await checkRoute("pricing");
    await checkRoute("settings");
  });

  it("should login and test CorruptedContentError behavior on both routes", async () => {
    // 1. GET /admin to extract anonymous cookie and csrfToken
    const getRes = await fetch(`${BASE_URL}/admin`);
    const anonCookie = getRes.headers.get("Set-Cookie");
    const text = await getRes.text();
    const csrfMatch = text.match(/name="csrfToken" value="([^"]+)"/);
    const csrfToken = csrfMatch ? csrfMatch[1] : "";

    // 2. POST /admin to login
    const loginRes = await fetch(`${BASE_URL}/admin`, {
      method: "POST",
      body: new URLSearchParams({ intent: "login", password: "test", csrfToken }),
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        "Origin": BASE_URL,
        "Cookie": anonCookie || "",
        "x-forwarded-for": "127.0.0.1"
      },
      redirect: "manual",
    });

    expect(loginRes.status).toBe(302);
    const authCookie = loginRes.headers.get("Set-Cookie") || "";
    expect(authCookie).toContain("__admin_session=");

    // GET /admin/pricing to extract new CSRF token
    const pricingRes = await fetch(`${BASE_URL}/admin/pricing`, {
        headers: { "Cookie": authCookie }
    });
    const pricingText = await pricingRes.text();
    const newCsrfMatch = pricingText.match(/name="csrfToken" value="([^"]+)"/);
    const newCsrfToken = newCsrfMatch ? newCsrfMatch[1] : "";
    const revMatch = pricingText.match(/name="revision" value="([^"]+)"/);
    const revision = revMatch ? revMatch[1] : "";

    // 3. Corrupt the JSON
    const corruptedData = Buffer.from("{ completely broken JSON");
    fs.writeFileSync(siteContentPath, corruptedData);

    const beforeFiles = fs.readdirSync(tempDir);

    const testRoute = async (route: string) => {
        const res = await fetch(`${BASE_URL}/admin/${route}`, {
            method: "POST",
            body: new URLSearchParams({ csrfToken: newCsrfToken, revision, pricing: "{}", business: "{}" }),
            headers: {
              "Content-Type": "application/x-www-form-urlencoded",
              "Origin": BASE_URL,
              "Cookie": authCookie,
              "x-forwarded-for": "127.0.0.1"
            },
            redirect: "manual",
        });

        expect(res.status).toBe(409);
        expect(fs.readFileSync(siteContentPath)).toEqual(corruptedData);
        expect(fs.readdirSync(tempDir)).toEqual(beforeFiles);
    };

    await testRoute("pricing");
    await testRoute("settings");

    // Restore valid JSON so afterAll doesn't fail on other things
    fs.copyFileSync(defaultContentPath, siteContentPath);
  });
});

describe("Real HTTP isolation WITHOUT admin config", () => {
  let serverProcess: ChildProcess;
  const PORT = 43210;
  const BASE_URL = `http://localhost:${PORT}`;

  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "timeless-noadmin-http-"));
  const dbPath = path.join(tempDir, "rate-limit.db");
  const siteContentPath = path.join(tempDir, "site-content.json");
  const defaultContentPath = path.resolve(__dirname, "../app/content/default-site-content.json");

  beforeAll(async () => {
    fs.copyFileSync(defaultContentPath, siteContentPath);

    return new Promise((resolve, reject) => {
      serverProcess = spawn("npm", ["run", "start"], {
        cwd: path.resolve(__dirname, ".."),
        env: {
          ...process.env,
          PORT: String(PORT),
          NODE_ENV: "production",
          PUBLIC_SITE_URL: BASE_URL,
          CONTACT_RATE_LIMIT_SECRET: "test-secret",
          RATE_LIMIT_DB_PATH: dbPath,
          SMTP_HOST: "localhost",
          SMTP_PORT: "2525",
          SMTP_USER: "test",
          SMTP_PASS: "test",
          SMTP_FROM: "from@example.com",
          SMTP_TO: "to@example.com",
          CONTACT_RATE_LIMIT_MAX: "10",
          TRUST_PROXY: "true",
          ADMIN_PASSWORD_HASH: "",
          ADMIN_SESSION_SECRET: "",
          SITE_CONTENT_PATH: siteContentPath,
          PORTFOLIO_CONTENT_PATH: path.join(tempDir, "portfolio.json"),
          PORTFOLIO_MEDIA_PATH: path.join(tempDir, "media")
        },
      });

      const timeout = setTimeout(() => reject(new Error("Server startup timeout")), 15000);

      serverProcess.stdout?.on("data", (data) => {
        if (data.toString().includes(String(PORT))) {
          clearTimeout(timeout);
          resolve(undefined);
        }
      });
      serverProcess.stderr?.on("data", (data) => console.error("Server error (no-admin):", data.toString()));
      serverProcess.on("error", (err) => {
        clearTimeout(timeout);
        reject(err);
      });
      serverProcess.on("exit", (code) => {
        clearTimeout(timeout);
        if (code !== 0 && code !== null) {
          reject(new Error(`Server exited with code ${code}`));
        }
      });
    });
  });

  afterAll(() => {
    if (serverProcess) serverProcess.kill();
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("GET /fr/ -> 200", async () => {
    const res = await fetch(`${BASE_URL}/fr/`);
    expect(res.status).toBe(200);
  });

  it("GET /en/contact -> 200", async () => {
    const res = await fetch(`${BASE_URL}/en/contact`);
    expect(res.status).toBe(200);
  });

  it("GET /admin -> 503 with safe error message", async () => {
    const res = await fetch(`${BASE_URL}/admin`);
    expect(res.status).toBe(503);
    const html = await res.text();
    expect(html).toContain("Administration temporairement indisponible");
    // Must not leak any secret variable name or stack trace
    expect(html).not.toContain("ADMIN_PASSWORD_HASH");
    expect(html).not.toContain("ADMIN_SESSION_SECRET");
    expect(html).not.toContain("Error:");
    expect(html).not.toMatch(/at\s+\S+\s+\(/); // no stack trace frames
  });

  it("POST /admin -> 503 with generic message", async () => {
    const res = await fetch(`${BASE_URL}/admin`, {
      method: "POST",
      body: new URLSearchParams({ password: "anything" }),
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        "Origin": BASE_URL,
        "x-forwarded-for": "127.0.0.1"
      },
      redirect: "manual",
    });
    expect(res.status).toBe(503);
    const html = await res.text();
    expect(html).toContain("Administration temporairement indisponible");
    expect(html).not.toContain("ADMIN_PASSWORD_HASH");
    expect(html).not.toContain("ADMIN_SESSION_SECRET");
  });
});
